// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: circuit.sql

package database

import (
	"github.com/shopspring/decimal"
)

type SaveCircuitsParams struct {
	ID       int32
	Ref      string
	Name     string
	Location *string
	Country  *string
	Lat      *decimal.Decimal
	Lng      *decimal.Decimal
	Alt      *int32
	Url      string
}
