// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: constructor.sql

package database

import (
	"github.com/shopspring/decimal"
)

type SaveConstructorResultsParams struct {
	ID            int32
	RaceID        int32
	ConstructorID int32
	Points        *decimal.Decimal
	Status        *string
}

type SaveConstructorStandingsParams struct {
	ID            int32
	RaceID        int32
	ConstructorID int32
	Points        decimal.Decimal
	Position      *int32
	PosText       *string
	Wins          int32
}

type SaveConstructorsParams struct {
	ID          int32
	Ref         string
	Name        string
	Nationality *string
	Url         string
}
