// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: driver.sql

package database

import (
	"time"

	"github.com/shopspring/decimal"
)

type SaveDriverStandingsParams struct {
	ID       int32
	RaceID   int32
	DriverID int32
	Points   decimal.Decimal
	Position *int32
	PosText  *string
	Wins     *int32
}

type SaveDriversParams struct {
	ID          int32
	Ref         string
	Number      *int32
	Code        *string
	FirstName   string
	LastName    string
	DateOfBirth *time.Time
	Nationality *string
	Url         string
}
