// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Circuit struct {
	ID       int32
	Ref      string
	Name     string
	Location *string
	Country  *string
	Lat      pgtype.Numeric
	Lng      pgtype.Numeric
	Alt      *int32
	Url      string
}

type Constructor struct {
	ID          int32
	Ref         string
	Name        string
	Nationality *string
	Url         string
}

type ConstructorResult struct {
	ID            int32
	RaceID        int32
	ConstructorID int32
	Points        pgtype.Numeric
	Status        *string
}

type ConstructorStanding struct {
	ID            int32
	RaceID        int32
	ConstructorID int32
	Points        pgtype.Numeric
	Position      *int32
	PosText       *string
	Wins          int32
}

type Driver struct {
	ID          int32
	Ref         string
	Number      *int32
	Code        *string
	FirstName   string
	LastName    string
	DateOfBirth *time.Time
	Nationality *string
	Url         string
}

type DriverStanding struct {
	ID       int32
	RaceID   int32
	DriverID int32
	Points   pgtype.Numeric
	Position *int32
	PosText  *string
	Wins     *int32
}

type LapTime struct {
	RaceID       int32
	DriverID     int32
	Lap          int32
	Position     *int32
	Time         *string
	Milliseconds *int32
}

type PitStop struct {
	RaceID       int32
	DriverID     int32
	Stop         int32
	Lap          int32
	Time         time.Time
	Duration     *string
	Milliseconds *int32
}

type Qualifying struct {
	ID            int32
	RaceID        int32
	DriverID      int32
	ConstructorID int32
	Number        int32
	Position      *int32
	Q1            *string
	Q2            *string
	Q3            *string
}

type Race struct {
	ID         int32
	Year       int32
	Round      int32
	CircuitID  int32
	Name       string
	Date       time.Time
	Time       *time.Time
	Url        *string
	Fp1Date    *time.Time
	Fp1Time    *time.Time
	Fp2Date    *time.Time
	Fp2Time    *time.Time
	Fp3Date    *time.Time
	Fp3Time    *time.Time
	QualiDate  *time.Time
	QualiTime  *time.Time
	SprintDate *time.Time
	SprintTime *time.Time
}

type Result struct {
	ID              int32
	RaceID          int32
	DriverID        int32
	ConstructorID   int32
	Number          *int32
	Grid            int32
	Position        *int32
	PosText         string
	PosOrder        int32
	Points          pgtype.Numeric
	Laps            int32
	Time            *string
	Milliseconds    *int32
	FastestLap      *int32
	Rank            *int32
	FastestLapTime  *string
	FastestLapSpeed *string
	StatusID        *int32
}

type Season struct {
	Year int32
	Url  string
}

type SprintResult struct {
	ID             int32
	RaceID         int32
	DriverID       int32
	ConstructorID  int32
	Number         int32
	Grid           int32
	Position       *int32
	PosText        string
	PosOrder       int32
	Points         pgtype.Numeric
	Laps           int32
	Time           *string
	Milliseconds   *int32
	FastestLap     *int32
	FastestLapTime *string
	StatusID       *int32
}

type Status struct {
	ID     int32
	Status string
}
