// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: iterators.go

package database

import (
	"context"
)

// iteratorForSaveCircuits implements pgx.CopyFromSource.
type iteratorForSaveCircuits struct {
	rows                 []SaveCircuitsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveCircuits) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveCircuits) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Ref,
		r.rows[0].Name,
		r.rows[0].Location,
		r.rows[0].Country,
		r.rows[0].Lat,
		r.rows[0].Lng,
		r.rows[0].Alt,
		r.rows[0].Url,
	}, nil
}

func (r iteratorForSaveCircuits) Err() error {
	return nil
}

func (q *Queries) SaveCircuits(ctx context.Context, arg []SaveCircuitsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"circuits"}, []string{"id", "ref", "name", "location", "country", "lat", "lng", "alt", "url"}, &iteratorForSaveCircuits{rows: arg})
}

// iteratorForSaveConstructorResults implements pgx.CopyFromSource.
type iteratorForSaveConstructorResults struct {
	rows                 []SaveConstructorResultsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveConstructorResults) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveConstructorResults) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RaceID,
		r.rows[0].ConstructorID,
		r.rows[0].Points,
		r.rows[0].Status,
	}, nil
}

func (r iteratorForSaveConstructorResults) Err() error {
	return nil
}

func (q *Queries) SaveConstructorResults(ctx context.Context, arg []SaveConstructorResultsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"constructor_results"}, []string{"id", "race_id", "constructor_id", "points", "status"}, &iteratorForSaveConstructorResults{rows: arg})
}

// iteratorForSaveConstructorStandings implements pgx.CopyFromSource.
type iteratorForSaveConstructorStandings struct {
	rows                 []SaveConstructorStandingsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveConstructorStandings) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveConstructorStandings) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RaceID,
		r.rows[0].ConstructorID,
		r.rows[0].Points,
		r.rows[0].Position,
		r.rows[0].PosText,
		r.rows[0].Wins,
	}, nil
}

func (r iteratorForSaveConstructorStandings) Err() error {
	return nil
}

func (q *Queries) SaveConstructorStandings(ctx context.Context, arg []SaveConstructorStandingsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"constructor_standings"}, []string{"id", "race_id", "constructor_id", "points", "position", "pos_text", "wins"}, &iteratorForSaveConstructorStandings{rows: arg})
}

// iteratorForSaveConstructors implements pgx.CopyFromSource.
type iteratorForSaveConstructors struct {
	rows                 []SaveConstructorsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveConstructors) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveConstructors) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Ref,
		r.rows[0].Name,
		r.rows[0].Nationality,
		r.rows[0].Url,
	}, nil
}

func (r iteratorForSaveConstructors) Err() error {
	return nil
}

func (q *Queries) SaveConstructors(ctx context.Context, arg []SaveConstructorsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"constructors"}, []string{"id", "ref", "name", "nationality", "url"}, &iteratorForSaveConstructors{rows: arg})
}

// iteratorForSaveDriverStandings implements pgx.CopyFromSource.
type iteratorForSaveDriverStandings struct {
	rows                 []SaveDriverStandingsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveDriverStandings) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveDriverStandings) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RaceID,
		r.rows[0].DriverID,
		r.rows[0].Points,
		r.rows[0].Position,
		r.rows[0].PosText,
		r.rows[0].Wins,
	}, nil
}

func (r iteratorForSaveDriverStandings) Err() error {
	return nil
}

func (q *Queries) SaveDriverStandings(ctx context.Context, arg []SaveDriverStandingsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"driver_standings"}, []string{"id", "race_id", "driver_id", "points", "position", "pos_text", "wins"}, &iteratorForSaveDriverStandings{rows: arg})
}

// iteratorForSaveDrivers implements pgx.CopyFromSource.
type iteratorForSaveDrivers struct {
	rows                 []SaveDriversParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveDrivers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveDrivers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Ref,
		r.rows[0].Number,
		r.rows[0].Code,
		r.rows[0].FirstName,
		r.rows[0].LastName,
		r.rows[0].DateOfBirth,
		r.rows[0].Nationality,
		r.rows[0].Url,
	}, nil
}

func (r iteratorForSaveDrivers) Err() error {
	return nil
}

func (q *Queries) SaveDrivers(ctx context.Context, arg []SaveDriversParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"drivers"}, []string{"id", "ref", "number", "code", "first_name", "last_name", "date_of_birth", "nationality", "url"}, &iteratorForSaveDrivers{rows: arg})
}

// iteratorForSaveLapTimes implements pgx.CopyFromSource.
type iteratorForSaveLapTimes struct {
	rows                 []SaveLapTimesParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveLapTimes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveLapTimes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RaceID,
		r.rows[0].DriverID,
		r.rows[0].Lap,
		r.rows[0].Position,
		r.rows[0].Time,
		r.rows[0].Milliseconds,
	}, nil
}

func (r iteratorForSaveLapTimes) Err() error {
	return nil
}

func (q *Queries) SaveLapTimes(ctx context.Context, arg []SaveLapTimesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"lap_times"}, []string{"race_id", "driver_id", "lap", "position", "time", "milliseconds"}, &iteratorForSaveLapTimes{rows: arg})
}

// iteratorForSavePitStops implements pgx.CopyFromSource.
type iteratorForSavePitStops struct {
	rows                 []SavePitStopsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSavePitStops) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSavePitStops) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RaceID,
		r.rows[0].DriverID,
		r.rows[0].Stop,
		r.rows[0].Lap,
		r.rows[0].Time,
		r.rows[0].Duration,
		r.rows[0].Milliseconds,
	}, nil
}

func (r iteratorForSavePitStops) Err() error {
	return nil
}

func (q *Queries) SavePitStops(ctx context.Context, arg []SavePitStopsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"pit_stops"}, []string{"race_id", "driver_id", "stop", "lap", "time", "duration", "milliseconds"}, &iteratorForSavePitStops{rows: arg})
}

// iteratorForSaveQualifyingResults implements pgx.CopyFromSource.
type iteratorForSaveQualifyingResults struct {
	rows                 []SaveQualifyingResultsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveQualifyingResults) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveQualifyingResults) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RaceID,
		r.rows[0].DriverID,
		r.rows[0].ConstructorID,
		r.rows[0].Number,
		r.rows[0].Position,
		r.rows[0].Q1,
		r.rows[0].Q2,
		r.rows[0].Q3,
	}, nil
}

func (r iteratorForSaveQualifyingResults) Err() error {
	return nil
}

func (q *Queries) SaveQualifyingResults(ctx context.Context, arg []SaveQualifyingResultsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"qualifying"}, []string{"id", "race_id", "driver_id", "constructor_id", "number", "position", "q1", "q2", "q3"}, &iteratorForSaveQualifyingResults{rows: arg})
}

// iteratorForSaveRaces implements pgx.CopyFromSource.
type iteratorForSaveRaces struct {
	rows                 []SaveRacesParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveRaces) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveRaces) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Year,
		r.rows[0].Round,
		r.rows[0].CircuitID,
		r.rows[0].Name,
		r.rows[0].Date,
		r.rows[0].Time,
		r.rows[0].Url,
		r.rows[0].Fp1Date,
		r.rows[0].Fp1Time,
		r.rows[0].Fp2Date,
		r.rows[0].Fp2Time,
		r.rows[0].Fp3Date,
		r.rows[0].Fp3Time,
		r.rows[0].QualiDate,
		r.rows[0].QualiTime,
		r.rows[0].SprintDate,
		r.rows[0].SprintTime,
	}, nil
}

func (r iteratorForSaveRaces) Err() error {
	return nil
}

func (q *Queries) SaveRaces(ctx context.Context, arg []SaveRacesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"races"}, []string{"id", "year", "round", "circuit_id", "name", "date", "time", "url", "fp1_date", "fp1_time", "fp2_date", "fp2_time", "fp3_date", "fp3_time", "quali_date", "quali_time", "sprint_date", "sprint_time"}, &iteratorForSaveRaces{rows: arg})
}

// iteratorForSaveResults implements pgx.CopyFromSource.
type iteratorForSaveResults struct {
	rows                 []SaveResultsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveResults) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveResults) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RaceID,
		r.rows[0].DriverID,
		r.rows[0].ConstructorID,
		r.rows[0].Number,
		r.rows[0].Grid,
		r.rows[0].Position,
		r.rows[0].PosText,
		r.rows[0].PosOrder,
		r.rows[0].Points,
		r.rows[0].Laps,
		r.rows[0].Time,
		r.rows[0].Milliseconds,
		r.rows[0].FastestLap,
		r.rows[0].Rank,
		r.rows[0].FastestLapTime,
		r.rows[0].FastestLapSpeed,
		r.rows[0].StatusID,
	}, nil
}

func (r iteratorForSaveResults) Err() error {
	return nil
}

func (q *Queries) SaveResults(ctx context.Context, arg []SaveResultsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"results"}, []string{"id", "race_id", "driver_id", "constructor_id", "number", "grid", "position", "pos_text", "pos_order", "points", "laps", "time", "milliseconds", "fastest_lap", "rank", "fastest_lap_time", "fastest_lap_speed", "status_id"}, &iteratorForSaveResults{rows: arg})
}

// iteratorForSaveSeasons implements pgx.CopyFromSource.
type iteratorForSaveSeasons struct {
	rows                 []SaveSeasonsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveSeasons) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveSeasons) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Year,
		r.rows[0].Url,
	}, nil
}

func (r iteratorForSaveSeasons) Err() error {
	return nil
}

func (q *Queries) SaveSeasons(ctx context.Context, arg []SaveSeasonsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"seasons"}, []string{"year", "url"}, &iteratorForSaveSeasons{rows: arg})
}

// iteratorForSaveSprintResults implements pgx.CopyFromSource.
type iteratorForSaveSprintResults struct {
	rows                 []SaveSprintResultsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveSprintResults) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveSprintResults) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].RaceID,
		r.rows[0].DriverID,
		r.rows[0].ConstructorID,
		r.rows[0].Number,
		r.rows[0].Grid,
		r.rows[0].Position,
		r.rows[0].PosText,
		r.rows[0].PosOrder,
		r.rows[0].Points,
		r.rows[0].Laps,
		r.rows[0].Time,
		r.rows[0].Milliseconds,
		r.rows[0].FastestLap,
		r.rows[0].FastestLapTime,
		r.rows[0].StatusID,
	}, nil
}

func (r iteratorForSaveSprintResults) Err() error {
	return nil
}

func (q *Queries) SaveSprintResults(ctx context.Context, arg []SaveSprintResultsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"sprint_results"}, []string{"id", "race_id", "driver_id", "constructor_id", "number", "grid", "position", "pos_text", "pos_order", "points", "laps", "time", "milliseconds", "fastest_lap", "fastest_lap_time", "status_id"}, &iteratorForSaveSprintResults{rows: arg})
}

// iteratorForSaveStatuses implements pgx.CopyFromSource.
type iteratorForSaveStatuses struct {
	rows                 []SaveStatusesParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveStatuses) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveStatuses) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Status,
	}, nil
}

func (r iteratorForSaveStatuses) Err() error {
	return nil
}

func (q *Queries) SaveStatuses(ctx context.Context, arg []SaveStatusesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"status"}, []string{"id", "status"}, &iteratorForSaveStatuses{rows: arg})
}
