// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: laptime.sql

package database

type SaveLapTimesParams struct {
	RaceID       int32
	DriverID     int32
	Lap          int32
	Position     *int32
	Time         *string
	Milliseconds *int32
}
