// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Circuit struct {
	ID       int32
	Ref      string
	Name     string
	Location pgtype.Text
	Country  pgtype.Text
	Lat      pgtype.Float8
	Lng      pgtype.Float8
	Alt      pgtype.Int4
	Url      string
}

type Constructor struct {
	ID          int32
	Ref         string
	Name        string
	Nationality pgtype.Text
	Url         string
}

type ConstructorResult struct {
	ID            int32
	RaceID        int32
	ConstructorID int32
	Points        pgtype.Float8
	Status        pgtype.Text
}

type ConstructorStanding struct {
	ID            int32
	RaceID        int32
	ConstructorID int32
	Points        float64
	Position      pgtype.Int4
	PositionText  pgtype.Text
	Wins          int32
}

type Driver struct {
	ID          int32
	Ref         string
	Number      pgtype.Int4
	Code        pgtype.Text
	FirstName   string
	LastName    string
	DateOfBirth pgtype.Date
	Nationality pgtype.Text
	Url         string
}

type DriverStanding struct {
	ID           int32
	RaceID       int32
	DriverID     int32
	Points       float64
	Position     pgtype.Int4
	PositionText pgtype.Text
	Wins         int32
}

type LapTime struct {
	RaceID       int32
	DriverID     int32
	Lap          int32
	Position     pgtype.Int4
	Time         pgtype.Text
	Milliseconds pgtype.Int4
}

type PitStop struct {
	RaceID       int32
	DriverID     int32
	Stop         int32
	Lap          int32
	Time         pgtype.Time
	Duration     pgtype.Text
	Milliseconds pgtype.Int4
}

type Qualifying struct {
	ID            int32
	RaceID        int32
	DriverID      int32
	ConstructorID int32
	Number        int32
	Position      pgtype.Int4
	Q1            pgtype.Text
	Q2            pgtype.Text
	Q3            pgtype.Text
}

type Race struct {
	ID         int32
	Year       int32
	Round      int32
	CircuitID  int32
	Name       string
	Date       pgtype.Date
	Time       pgtype.Time
	Url        pgtype.Text
	Fp1Date    pgtype.Date
	Fp1Time    pgtype.Time
	Fp2Date    pgtype.Date
	Fp2Time    pgtype.Time
	Fp3Date    pgtype.Date
	Fp3Time    pgtype.Time
	QualiDate  pgtype.Date
	QualiTime  pgtype.Time
	SprintDate pgtype.Date
	SprintTime pgtype.Time
}

type Result struct {
	ID              int32
	RaceID          int32
	DriverID        int32
	ConstructorID   int32
	Number          pgtype.Int4
	Grid            int32
	Position        pgtype.Int4
	PositionText    string
	PositionOrder   int32
	Points          float64
	Laps            int32
	Time            pgtype.Text
	Milliseconds    pgtype.Int4
	FastestLap      pgtype.Int4
	Rank            pgtype.Int4
	FastestLapTime  pgtype.Text
	FastestLapSpeed pgtype.Text
	StatusID        int32
}

type Season struct {
	Year int32
	Url  string
}

type SprintResult struct {
	ID             int32
	RaceID         int32
	DriverID       int32
	ConstructorID  int32
	Number         int32
	Grid           int32
	Position       pgtype.Int4
	PositionText   string
	PositionOrder  int32
	Points         float64
	Laps           int32
	Time           pgtype.Text
	Milliseconds   pgtype.Int4
	FastestLap     pgtype.Int4
	FastestLapTime pgtype.Text
	StatusID       int32
}

type Status struct {
	ID     int32
	Status string
}
