// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: pitstop.sql

package database

import (
	"time"
)

type SavePitStopsParams struct {
	RaceID       int32
	DriverID     int32
	Stop         int32
	Lap          int32
	Time         time.Time
	Duration     *string
	Milliseconds *int32
}
