// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: qualifying.sql

package database

type SaveQualifyingResultsParams struct {
	ID            int32
	RaceID        int32
	DriverID      int32
	ConstructorID int32
	Number        int32
	Position      *int32
	Q1            *string
	Q2            *string
	Q3            *string
}
