// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: race.sql

package database

import (
	"time"
)

type SaveRacesParams struct {
	ID         int32
	Year       int32
	Round      int32
	CircuitID  int32
	Name       string
	Date       time.Time
	Time       *time.Time
	Url        *string
	Fp1Date    *time.Time
	Fp1Time    *time.Time
	Fp2Date    *time.Time
	Fp2Time    *time.Time
	Fp3Date    *time.Time
	Fp3Time    *time.Time
	QualiDate  *time.Time
	QualiTime  *time.Time
	SprintDate *time.Time
	SprintTime *time.Time
}
