// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: season.sql

package database

import (
	"context"

	"github.com/shopspring/decimal"
)

const getDriverStandingsByYear = `-- name: GetDriverStandingsByYear :many
SELECT
    d.id AS driver_id,
    d.first_name,
    d.last_name,
    sum(re.points) AS points
FROM results AS re
INNER JOIN drivers AS d ON re.driver_id = d.id
INNER JOIN races AS r ON re.race_id = r.id
WHERE r.year = $1
GROUP BY d.id
ORDER BY points DESC
`

type GetDriverStandingsByYearRow struct {
	DriverID  int32
	FirstName string
	LastName  string
	Points    decimal.Decimal
}

func (q *Queries) GetDriverStandingsByYear(ctx context.Context, year int32) ([]GetDriverStandingsByYearRow, error) {
	rows, err := q.db.Query(ctx, getDriverStandingsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDriverStandingsByYearRow
	for rows.Next() {
		var i GetDriverStandingsByYearRow
		if err := rows.Scan(
			&i.DriverID,
			&i.FirstName,
			&i.LastName,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
