version: '3'

dotenv: ['.direnv']

tasks:
  db:codegen:
    cmds:
      - cmd: sqlc generate
        silent: true
      - cmd: echo "Codegen complete"
        silent: true

  db:down:
    dir: "{{.TASKFILE_DIR}}/docker"
    cmds:
      - cmd: docker compose -f compose-dev.yaml down

  db:up:
    dir: "{{.TASKFILE_DIR}}/docker"
    cmds:
      - cmd: docker compose -f compose-dev.yaml up --wait
        silent: true

  db:update:
    cmds:
      - task: db:migrate
      - task: db:codegen

  db:migrate:
    dir: "{{.TASKFILE_DIR}}/sql/schema"
    cmds:
      - cmd: goose up
        silent: true

  db:migrate:down:
    dir: "{{.TASKFILE_DIR}}/sql/schema"
    cmds:
      - cmd: goose down
        silent: true

  db:migrate:new:
    dir: "{{.TASKFILE_DIR}}/sql/schema"
    cmds:
      - cmd: goose create {{.CLI_ARGS}} sql
        silent: true

  dev:
    cmds:
      - task: db:up
      - cmd: air
