version: '3'

dotenv: ['.direnv']

tasks:
  db:codegen:
    cmds:
      - cmd: sqlc generate
        silent: true
      - cmd: echo "Codegen complete"
        silent: true

  db:down:
    dir: "{{.TASKFILE_DIR}}/docker"
    cmds:
      - cmd: docker compose -f compose-dev.yaml down

  db:migrate:
    dir: "{{.TASKFILE_DIR}}/sql/schema"
    cmds:
      - cmd: goose up
        silent: true

  db:migrate:create:
    dir: "{{.TASKFILE_DIR}}/sql/schema"
    cmds:
      - cmd: goose create {{.CLI_ARGS}} sql
        silent: true

  db:migrate:down:
    dir: "{{.TASKFILE_DIR}}/sql/schema"
    cmds:
      - cmd: goose down
        silent: true

  db:push:
    cmds:
      - cmd: docker commit -a "Jarrod Seccombe <jarrod.seccombe@icloud.com>" $(docker ps -aqf "name=f1db-seed") ghcr.io/jsec/f1db
      - cmd: echo $CR_PAT | docker login ghcr.io -u jsec --password-stdin
        silent: true
      - cmd: docker push ghcr.io/jsec/f1db:latest

  db:up:
    dir: "{{.TASKFILE_DIR}}/docker"
    cmds:
      - cmd: docker compose -f compose-dev.yaml up --wait

  db:update:
    cmds:
      - task: db:migrate
      - task: db:codegen

  dev:
    cmds:
      - task: db:up

  image:up:
    dir: "{{.TASKFILE_DIR}}/docker"
    cmds:
      - cmd: docker compose -f compose-seed.yaml up --wait
        silent: true
      - task: db:migrate

  image:down:
    dir: "{{.TASKFILE_DIR}}/docker"
    cmds:
      - cmd: docker compose -f compose-seed.yaml down
        silent: true

  image:new:
    cmds:
      - task: image:up
      - cmd: go run ./cmd/imager
        silent: true
      - task: db:push
      - task: image:down
